# Argon 475 RDF  

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
library(hadron)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
myplotly(ggplot())
#widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```






```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL
for (T in c(90, 110, 240)){
#for (T in c( 80, 140, 190)){
  file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/",T,
               "K/out/RDF_Ar-475_",T,"K.txt_raw_correlators")
  mt1<-read_df(file)
  all_obs1<- get_all_corr(mt1)
  
  df<-add_corr_to_df(string = paste0("cold-T",T,"K"),all_obs=all_obs1,mt=mt1,df=df,
                     log = FALSE, number = 1,nudge = 0,print_res = FALSE)
  
  #################


# }
# for (T in c(100, 200, 240)){
#for (T in c( 80, 140, 190)){
  file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/",T,
               "K/out/RDF_Ar-475_",T,"K.txt_raw_correlators")
  mt1<-read_df(file)
  all_obs1<- get_all_corr(mt1)
  
  df<-add_corr_to_df(string = paste0("hot-T",T,"K"),all_obs=all_obs1,mt=mt1,df=df,
                     log = FALSE, number = 1,nudge = 0,print_res = FALSE)
  
  #################
 
  

}
df$x <- df$x*0.0333333333
gg<- plot_df_corr_ggplot(df,noribbon = TRUE, width=0.1)

fig<- myplotly(gg,"","r [A]", '$g(r)$', to_print=TRUE )

```