# checks (legacy run) 

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
#widgetframe::frameableWidget(ggplotly(ggp)#%>%config(mathjax = "cdn") )
```


```{r,  results='asis', warning=FALSE}

library(hadron)

dfa<-data.frame()
dts<-c("4e-4" )
dir<-"/home/garofalo/analysis/chemHMC/Argon/VII/"
dts<- c("4e-4")
for (dt  in dts) {
  file <- paste0(dir,"V_read_",dt,".txt")
  df<-read.table(file)
  df$eps<-dt
  df$start<-"read"
  df$t<-c(1:length(df[,1]))
  dfa<-rbind(dfa,df)
}

```



```{r, echo=FALSE, results='asis', warning=FALSE}
lines<-seq(1,dim(dfa)[1], by=1e+4)
gg<- myggplot(shape = FALSE, fill = FALSE)
gg<- gg+ geom_line(aes(x=dfa$t[lines], y=dfa[lines,1]+100))
gg<- gg+scale_y_continuous(trans='log10')+geom_vline(xintercept = 20e+3)
fig<-myplotly(gg,"","t(HMC)","U+100", xrange = c(0,1020e+3),
         yrange = c(1.9,2.1),legend_title = "dt, start", legend_position = c(0.8,0.95), to_print = FALSE)
fig
noterm<-seq(2e+4,dim(dfa)[1],by=1000)
dh<-uwerrprimary(dfa[noterm,1])
cat("$\\langle U\\rangle$=",mean_print(dh$value,dh$dvalue),
    "  $\\tau_{int}=$",mean_print(dh$tauint,dh$dtauint),"\n\n" )
# gg<- gg+xlab("ntraj") + ylab("U+100")
# gg
```


```{r, echo=FALSE, results='asis', warning=FALSE}
dfh<-read.table(paste0(dir,"Ar-VII_dh_exp_mdh.txt"))
fun <- function(m){
  return(m[1])
}
# dh<-uwerr(fun, dfh[,1], nrep=c(length(dfh[,1])), S = 1.5, pl = FALSE)
dh<-uwerrprimary(dfh[,1])
cat("$\\langle\\delta H\\rangle$=",mean_print(dh$value,dh$dvalue),
    "  $\\tau_{int}=$",mean_print(dh$tauint,dh$dtauint),"\n\n" )

exp_mdh<-uwerrprimary(dfh[,2])
cat("$\\langle e^{-\\delta H}\\rangle$=",mean_print(exp_mdh$value,exp_mdh$dvalue),
    "  $\\tau_{int}=$",mean_print(exp_mdh$tauint,exp_mdh$dtauint),"\n\n" )

gg<- myggplot(shape = FALSE, fill = FALSE)
gg<- gg+  geom_line(aes(x=c(1:length(dfh[lines,1])), y=dfh[lines,1]))
# gg<- ggplot(dfh,aes( dfh[,1]) )+ geom_histogram(bins = 100 ) +theme_bw()
# gg<- gg+xlab("$\\delta H$")
# gg

 # gg
 fig<-myplotly(gg,"",xlabel="ntraj","$\\delta H$",to_print = TRUE)
 
 cat("<br /> ")
 
 gg<- ggplot(dfh,aes( dfh[,1]) )+ geom_histogram(bins = 100 ) +theme_bw()
fig1<-myplotly(gg,xlabel ="$\\delta H$",  to_print = TRUE)


```

<br /> 

```{r, echo=FALSE, results='asis', warning=FALSE}
gg<- myggplot(shape = FALSE, fill = FALSE)
gg<- gg+  geom_line(aes(x=c(1:length(dfh[lines,1])), y=dfh[lines,2]))
# gg<- ggplot(dfh,aes( dfh[,2]) )+ geom_histogram(bins = 100 ) +theme_bw()
# gg<- gg+xlab("$e^{-\\delta H$}$")

# gg
fig<-myplotly(gg,"","ntraj","$e^{-\\delta H}$", to_print = TRUE)
 cat("<br /> ")

gg<- ggplot(dfh,aes( dfh[,2]) )+ geom_histogram(bins = 100 ) +theme_bw()
fig1<-myplotly(gg,xlabel ="$e^{-\\delta H}$" , to_print = TRUE)

```