# Selected case 475 90K 

Here we are comparing the result of the HMC with

```{.yaml}
StartCondition: read
start_configuration_file: out_Ar-475_300K.xyz 
output_file: out_Ar-475_90K.xyz
append: false
seed: 1
rng_host_state: rng_host
rng_device_state: rng_device
Ntrajectories: 110e+4 
thermalization_steps: 10e+4
save_every: 1e+4

geometry: 
  Lx: 26.8 
  Ly: 26.8
  Lz: 26.8

particles:
  name: identical_particles
  name_xyz: Ar
  N: 475
  mass: 39.948   
  beta: 128.9390902416176
  cutoff: 12.0  
  eps: 0.01042332126  
  sigma: 3.4
  algorithm: all_neighbour_inner_parallel 
  RDF:
    Lmax: 12
    size_bin: 0.033333  
    output_file: RDF_Ar-475_90K.txt

integrator:
  name: OMF4
  dt: 5e-3
  steps: 20
```


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
library(hadron)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
#widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```

```{r, echo=FALSE}
sampling<-500
```

## cold

```{r, echo=FALSE, results='asis', warning=FALSE}

dfall_cold<-data.frame("T"=c(0),
                "H"=c(0),"errH"=c(0),
                "K"=c(0),"dK"=c(0),
                "V"=c(0),"dV"=c(0),
                "dH"=c(0),"ddH"=c(0),
                "exp(-dH)"=c(0),"dexp(-dH)"=c(0)
                )
count<-1
T<-90
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/",T,"K/HMC_hystory_",T,"K.txt")


if(file.exists(file)){

    dft<-data.frame("obs"=c("K","V","dH","exp(-dH)"), "ave"=rep(1,4), "tauint"=rep(1,4) )
    df<-read.table(file, header = TRUE)
    myl<-list(T,2,3,4,5)
    cat("sampling every ",sampling," trajectories \n\n")
    lines<-seq(sampling,length(df[,1]),sampling)
    
    for (i in c(1,2,3,4)){
      tmp<-uwerrprimary(df[lines,i+1])
      myl[[2+(i-1)*2]]<-tmp$value
      myl[[3+(i-1)*2]]<-tmp$dvalue
      
      dft[i,2]<- mean_print(tmp$value,tmp$dvalue)
      dft[i,3]<- mean_print(tmp$tauint,tmp$dtauint)
    }
    dfall_cold[count, ]<- myl
    count<- count+1
    print(kable(dft))
}
  

```


## hot

```{r, echo=FALSE, results='asis', warning=FALSE}

dfall_hot<-data.frame("T"=c(0),
                "H"=c(0),"errH"=c(0),
                "K"=c(0),"dK"=c(0),
                "V"=c(0),"dV"=c(0),
                "dH"=c(0),"ddH"=c(0),
                "exp(-dH)"=c(0),"dexp(-dH)"=c(0)
                )
count<-1
T<-90
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/",T,"K/HMC_hystory_",T,"K.txt")


if(file.exists(file)){

    dft<-data.frame("obs"=c("K","V","dH","exp(-dH)"), "ave"=rep(1,4), "tauint"=rep(1,4) )
    df<-read.table(file, header = TRUE)
    myl<-list(T,2,3,4,5)
    cat("sampling every ",sampling," trajectories \n\n")
    lines<-seq(sampling,length(df[,1]),sampling)
    
    for (i in c(1,2,3,4)){
      tmp<-uwerrprimary(df[lines,i+1])
      myl[[2+(i-1)*2]]<-tmp$value
      myl[[3+(i-1)*2]]<-tmp$dvalue
      
      dft[i,2]<- mean_print(tmp$value,tmp$dvalue)
      dft[i,3]<- mean_print(tmp$tauint,tmp$dtauint)
    }
    dfall_hot[count, ]<- myl
    count<- count+1
    print(kable(dft))
}
  

```


<!-- ## hot no regression test -->

<!-- ```{r, echo=FALSE, results='asis', warning=FALSE} -->

<!-- dfall_hot_nor<-data.frame("T"=c(0), -->
<!--                 "H"=c(0),"errH"=c(0), -->
<!--                 "K"=c(0),"dK"=c(0), -->
<!--                 "V"=c(0),"dV"=c(0), -->
<!--                 "dH"=c(0),"ddH"=c(0), -->
<!--                 "exp(-dH)"=c(0),"dexp(-dH)"=c(0) -->
<!--                 ) -->
<!-- count<-1 -->
<!-- T<-90 -->
<!-- file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/test_traj/",T,"K_no_regression_test/HMC_hystory_",T,"K.txt") -->


<!-- if(file.exists(file)){ -->

<!--     dft<-data.frame("obs"=c("K","V","dH","exp(-dH)"), "ave"=rep(1,4), "tauint"=rep(1,4) ) -->
<!--     df<-read.table(file, header = TRUE) -->
<!--     myl<-list(T,2,3,4,5) -->
<!--     cat("sampling every ",sampling," trajectories \n\n") -->
<!--     lines<-seq(sampling,length(df[,1]),sampling) -->

<!--     for (i in c(1,2,3,4)){ -->
<!--       tmp<-uwerrprimary(df[lines,i+1]) -->
<!--       myl[[2+(i-1)*2]]<-tmp$value -->
<!--       myl[[3+(i-1)*2]]<-tmp$dvalue -->

<!--       dft[i,2]<- mean_print(tmp$value,tmp$dvalue) -->
<!--       dft[i,3]<- mean_print(tmp$tauint,tmp$dtauint) -->
<!--     } -->
<!--     dfall_hot_nor[count, ]<- myl -->
<!--     count<- count+1 -->
<!--     print(kable(dft)) -->
<!-- } -->


<!-- ``` -->


## hot random traj


```{r, echo=FALSE, results='asis', warning=FALSE}

dfall_hot_bt<-data.frame("T"=c(0),
                "H"=c(0),"errH"=c(0),
                "K"=c(0),"dK"=c(0),
                "V"=c(0),"dV"=c(0),
                "dH"=c(0),"ddH"=c(0),
                "exp(-dH)"=c(0),"dexp(-dH)"=c(0)
                )
count<-1
T<-90
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/test_traj/",T,"K_binomial_traj/HMC_hystory_",T,"K.txt")


if(file.exists(file)){

    dft<-data.frame("obs"=c("K","V","dH","exp(-dH)"), "ave"=rep(1,4), "tauint"=rep(1,4) )
    df<-read.table(file, header = TRUE)
    myl<-list(T,2,3,4,5)
    cat("sampling every ",sampling," trajectories \n\n")
    lines<-seq(sampling,length(df[,1]),sampling)
    
    for (i in c(1,2,3,4)){
      tmp<-uwerrprimary(df[lines,i+1])
      myl[[2+(i-1)*2]]<-tmp$value
      myl[[3+(i-1)*2]]<-tmp$dvalue
      
      dft[i,2]<- mean_print(tmp$value,tmp$dvalue)
      dft[i,3]<- mean_print(tmp$tauint,tmp$dtauint)
    }
    dfall_hot_bt[count, ]<- myl
    count<- count+1
    print(kable(dft))
}
  

```


### steps distribution

```{r, echo=FALSE, results='asis', warning=FALSE}
T<-90
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/test_traj/",T,"K_binomial_traj/steps_hystory.txt")
tmp<-read.table(file)
gg<- ggplot(tmp,aes( tmp[,3]) )+ geom_histogram(bins=100) +theme_bw()
fig1<-myplotly(gg,xlabel ="$H$" , to_print = TRUE)
```




## HMC hystory (with thermalization)

```{r, echo=FALSE, results='asis', warning=FALSE}
T<-90
dfa<-NULL

################
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/",T,"K/HMC_hystory_notherm_",T,"K.txt")
tmp<-read.table(file, header = TRUE)
lines<-seq(sampling,length(tmp[,1]),sampling)
tmp<-tmp[lines,]
tmp$t<-c(1:length(tmp[,1]))
tmp$label<-"hot-start"
dfa<-rbind(dfa,tmp[,])

################
# file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/test_traj/",T,"K_no_regression_test/HMC_hystory_notherm_",T,"K.txt")
# tmp<-read.table(file, header = TRUE)
# lines<-seq(sampling,length(tmp[,1]),sampling)
# tmp<-tmp[lines,]
# tmp$t<-c(1:length(tmp[,1]))
# tmp$label<-"hot-start-regression"
# dfa<-rbind(dfa,tmp[,])
################

file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/",T,"K/HMC_hystory_notherm_",T,"K.txt")
tmp<-read.table(file, header = TRUE)
lines<-seq(sampling,length(tmp[,1]),sampling)
tmp<-tmp[lines,]
tmp$t<-c(1:length(tmp[,1]))
tmp$label<-"cold-start"
dfa<-rbind(dfa,tmp[,])
################
################
file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/test_traj/",T,"K_binomial_traj/HMC_hystory_notherm_",T,"K.txt")
tmp<-read.table(file, header = TRUE)
lines<-seq(sampling,length(tmp[,1]),sampling)
tmp<-tmp[lines,]
tmp$t<-c(1:length(tmp[,1]))
tmp$label<-"hot-start-rand_traj"
dfa<-rbind(dfa,tmp[,])
################


gg<- ggplot()+theme_bw()#myggplot(shape = FALSE, fill = FALSE)
gg<- gg+ geom_line(aes(x=dfa$t, y=dfa$V, color=dfa$label))
#gg<- gg+scale_y_continuous(trans='log10')+geom_vline(xintercept = 20e+3)
fig<-myplotly(gg,"","t(HMC)","U",
              legend_title = "", legend_position = c(0.8,0.95), to_print = TRUE)

#noterm<-seq(2e+4,dim(dfa)[1],by=1000)
```

## RDF


```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL
for (T in c(90)){
#for (T in c( 80, 140, 190)){
  file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/",T,
               "K/out/RDF_Ar-475_",T,"K.txt_raw_correlators")
  mt1<-read_df(file)
  all_obs1<- get_all_corr(mt1)
  
  df<-add_corr_to_df(string = paste0("T",T,"K-cold-start"),all_obs=all_obs1,mt=mt1,df=df,
                     log = FALSE, number = 1,nudge = 0,print_res = FALSE,
                     rename =paste0("T",T,"K-cold-start") )
  #################
  
  file<-paste0("/home/garofalo/analysis/chemHMC/Argon/Ar-475/hot_start/",T,
               "K/out/RDF_Ar-475_",T,"K.txt_raw_correlators")
  mt1<-read_df(file)
  all_obs1<- get_all_corr(mt1)
  
  df<-add_corr_to_df(string = paste0("T",T,"K-hot-start"),all_obs=all_obs1,mt=mt1,df=df,
                     log = FALSE, number = 1,nudge = 0,print_res = FALSE,
                     rename=paste0("T",T,"K-hot-start"))
  #################
  

}
df$x <- df$x*0.0333333333
gg<- plot_df_corr_ggplot(df,noribbon = TRUE, width=0.1)

fig<- myplotly(gg,"","r [A]", '$g(r)$', to_print=TRUE )

```

